In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\ADITYA SINGH\Desktop\Project 1 - Mercedes-Benz Greener Manufacturing\train.csv")
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [3]:
df.drop(columns=["ID"],inplace=True)
df.head()

y  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  \
0  130.81   k  v  at  a  d  u  j  o    0  ...     0     0     1     0     0   
1   88.53   k  t  av  e  d  y  l  o    0  ...     1     0     0     0     0   
2   76.26  az  w   n  c  d  x  j  x    0  ...     0     0     0     0     0   
3   80.62  az  t   n  f  d  x  l  e    0  ...     0     0     0     0     0   
4   78.02  az  v   n  f  d  h  d  n    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 377 columns]

In [22]:
def check_var(df):
    l=[]
    for i in df.columns:
        l.append(i)
    for i in range(9,len(l)):
        if df.var()[l[i]]==0:
            df.drop(columns=[l[i]], inplace=True)
            print(l[i])
check_var(df)
df.head()  

X0  X1  X2  X3  X4  X5  X6  X8  X10  X12  ...  X375  X376  X377  X378  \
0  32  23  17   0   3  24   9  14    0    0  ...     0     0     1     0   
1  32  21  19   4   3  28  11  14    0    0  ...     1     0     0     0   
2  20  24  34   2   3  27   9  23    0    0  ...     0     0     0     0   
3  20  21  34   5   3  27  11   4    0    0  ...     0     0     0     0   
4  20  23  34   5   3  12   3  13    0    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 364 columns]

In [5]:
df.isnull().values.any()
        

False

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()   
df["X0"]=le.fit_transform(df["X0"])
df["X1"]=le.fit_transform(df["X1"])
df["X2"]=le.fit_transform(df["X2"])
df["X3"]=le.fit_transform(df["X3"])
df["X4"]=le.fit_transform(df["X4"])
df["X5"]=le.fit_transform(df["X5"])
df["X6"]=le.fit_transform(df["X6"])
df["X8"]=le.fit_transform(df["X8"])
df.head()

y  X0  X1  X2  X3  X4  X5  X6  X8  X10  ...  X375  X376  X377  X378  \
0  130.81  32  23  17   0   3  24   9  14    0  ...     0     0     1     0   
1   88.53  32  21  19   4   3  28  11  14    0  ...     1     0     0     0   
2   76.26  20  24  34   2   3  27   9  23    0  ...     0     0     0     0   
3   80.62  20  21  34   5   3  27  11   4    0  ...     0     0     0     0   
4   78.02  20  23  34   5   3  12   3  13    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 365 columns]

In [7]:
y=df.y
df.drop(columns=["y"],inplace=True)
df.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X12  ...  X375  X376  X377  X378  \
0  32  23  17   0   3  24   9  14    0    0  ...     0     0     1     0   
1  32  21  19   4   3  28  11  14    0    0  ...     1     0     0     0   
2  20  24  34   2   3  27   9  23    0    0  ...     0     0     0     0   
3  20  21  34   5   3  27  11   4    0    0  ...     0     0     0     0   
4  20  23  34   5   3  12   3  13    0    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 364 columns]

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(df)


In [9]:
from sklearn.decomposition import PCA
pca=PCA(n_components=50)
x_pca=pca.fit_transform(x)
x_pca

array([[ 12.25440456,  -2.94381394,  -0.95722339, ...,  33.36897674,
         -6.30476965, -25.55306388],
       [ -0.10255833,   0.366051  ,   0.99716348, ...,   0.65641825,
          0.61567988,   0.92444831],
       [ 10.27835977,  21.104837  ,  -5.01344326, ...,   1.65814432,
         -2.63710778,  -0.73682325],
       ...,
       [  0.43696249,   0.89754128,   3.44526929, ...,   0.27562036,
          0.21183421,   0.33114328],
       [ -1.34166585,   0.58923553,  -0.10968794, ...,   0.0713262 ,
          0.34185318,  -0.98025317],
       [ -2.16820694,  -1.06042799,  -0.28800541, ...,  -0.20831343,
         -0.43958011,   0.41453259]])

In [10]:
x_pca.shape


(4209, 50)

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_pca, y, test_size = 0.25)

In [18]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
xg_reg1 = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.6, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 100)
xg_reg1.fit(x_train,y_train)
preds = xg_reg1.predict(x_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))

[20:09:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.2.0/src/objective/regression_obj.cu:174: reg:linear is now deprecated in favor of reg:squarederror.
[20:09:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.2.0/src/objective/regression_obj.cu:174: reg:linear is now deprecated in favor of reg:squarederror.
RMSE: 8.269915


In [19]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.6, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 100)
xg_reg.fit(x_pca,y)

[20:10:51] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.2.0/src/objective/regression_obj.cu:174: reg:linear is now deprecated in favor of reg:squarederror.
[20:10:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.2.0/src/objective/regression_obj.cu:174: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.6, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=5,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=0, num_parallel_tree=1,
             objective='reg:linear', random_state=0, reg_alpha=10, reg_lambda=1,
             scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [21]:
test=pd.read_csv(r"C:\Users\ADITYA SINGH\Desktop\Project 1 - Mercedes-Benz Greener Manufacturing\test.csv")
test.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [24]:
test.drop(columns=["ID"],inplace=True)
check_var(test)
print("None values:",df.isnull().values.any())

X257
X258
X295
X296
X369
None values: False


In [25]:
test["X0"]=le.fit_transform(test["X0"])
test["X1"]=le.fit_transform(test["X1"])
test["X2"]=le.fit_transform(test["X2"])
test["X3"]=le.fit_transform(test["X3"])
test["X4"]=le.fit_transform(test["X4"])
test["X5"]=le.fit_transform(test["X5"])
test["X6"]=le.fit_transform(test["X6"])
test["X8"]=le.fit_transform(test["X8"])
test.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X11  ...  X375  X376  X377  X378  \
0  21  23  34   5   3  26   0  22    0    0  ...     0     0     0     1   
1  42   3   8   0   3   9   6  24    0    0  ...     0     0     1     0   
2  21  23  17   5   3   0   9   9    0    0  ...     0     0     0     1   
3  21  13  34   5   3  31  11  13    0    0  ...     0     0     0     1   
4  45  20  17   2   3  30   8  12    0    0  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 371 columns]

In [26]:
x_t = sc.fit_transform(test)
pca=PCA(n_components=50)
xt_pca=pca.fit_transform(x_t)
xt_pca

array([[  8.10074861,  20.96444628,  -8.85995413, ...,  -0.8121221 ,
         -2.34979703,  -1.93782395],
       [  1.07353107,  -4.72632072, -10.07626181, ...,   1.01659906,
         -2.68295422,  -0.93437649],
       [  5.83298528,  18.63937234,  -6.44727199, ...,   2.37752866,
         -1.77172631,  -0.54569576],
       ...,
       [ -2.63766636,   0.99728702,   3.05365016, ...,  -0.51708561,
          0.92540688,   0.51761482],
       [ -1.18958209,   0.74850593,   4.24890554, ...,   0.38318128,
         -0.65394148,   0.03726886],
       [ -1.51124446,  -2.20346537,  -3.48984618, ...,   0.31859406,
          0.3454316 ,   0.49478795]])

In [30]:
test_pred=xg_reg.predict(xt_pca)
print(test_pred)

[ 92.8556   103.77669   92.83944  ... 100.10008  108.38534   98.282265]


In [29]:
test["y"]=test_pred
test.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X11  ...  X376  X377  X378  X379  \
0  21  23  34   5   3  26   0  22    0    0  ...     0     0     1     0   
1  42   3   8   0   3   9   6  24    0    0  ...     0     1     0     0   
2  21  23  17   5   3   0   9   9    0    0  ...     0     0     1     0   
3  21  13  34   5   3  31  11  13    0    0  ...     0     0     1     0   
4  45  20  17   2   3  30   8  12    0    0  ...     0     0     0     0   

   X380  X382  X383  X384  X385           y  
0     0     0     0     0     0   92.855598  
1     0     0     0     0     0  103.776688  
2     0     0     0     0     0   92.839439  
3     0     0     0     0     0   90.990082  
4     0     0     0     0     0  106.992371  

[5 rows x 372 columns]